<<<<<<< HEAD
CREATE DATABASE  IF NOT EXISTS `telcoservice_db` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `telcoservice_db`;

DROP TABLE IF EXISTS `order`;
CREATE TABLE `order` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CLIENT` varchar(255) DEFAULT NULL,
  `HOURCREATION` time DEFAULT NULL,
  `DATECREATION` date DEFAULT NULL,
  `VALIDITYID` int DEFAULT NULL,
  `PACKAGEID` date DEFAULT NULL,
  `DATESUBSCRPTION` date DEFAULT NULL, -- consider fixing it to DATESUBSCRIPTION
  `TOTALCOST` decimal(5, 2) DEFAULT NULL, 
  `ISVALID` enum('DEFAULT', 'REJECTED', 'ACCEPTED'),
  `NUMBER_REJECTION` int DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `CLIENT` (`CLIENT`) ,
  KEY `VALIDITYID` (`VALIDITYID`),
  CONSTRAINT `order_ibfk_1` FOREIGN KEY (`CLIENT`)
   REFERENCES `client` (`USERNAME`)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  CONSTRAINT `order_ibfk_2` FOREIGN KEY (`VALIDITYID`)
   REFERENCES `validity` (`ID`)
      ON DELETE RESTRICT
      ON UPDATE RESTRICT
   CONSTRAINT `order_chk_1` 
   	CHECK ((`NUMBER_REJECTION` >= 0))
);
=======
CREATE DATABASE  IF NOT EXISTS `telcoservice_db` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `telcoservice_db`;

DROP TABLE IF EXISTS `order`;
CREATE TABLE `order` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CLIENT` varchar(255) DEFAULT NULL,
  `HOURCREATION` time DEFAULT NULL,
  `DATECREATION` date DEFAULT NULL,
  `VALIDITYID` int DEFAULT NULL,
  `PACKAGEID` date DEFAULT NULL,
  `DATESUBSCRPTION` date DEFAULT NULL, -- consider fixing it to DATESUBSCRIPTION
  `TOTALCOST` decimal(5, 2) DEFAULT NULL, 
  `ISVALID` enum('DEFAULT', 'REJECTED', 'ACCEPTED'),
  `NUMBER_REJECTION` int DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `CLIENT` (`CLIENT`) ,
  KEY `VALIDITYID` (`VALIDITYID`),
  CONSTRAINT `order_ibfk_1` FOREIGN KEY (`CLIENT`)
   REFERENCES `client` (`USERNAME`)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  CONSTRAINT `order_ibfk_2` FOREIGN KEY (`VALIDITYID`)
   REFERENCES `validity` (`ID`)
      ON DELETE RESTRICT
      ON UPDATE RESTRICT
   CONSTRAINT `order_chk_1` 
   	CHECK ((`NUMBER_REJECTION` >= 0))
);
>>>>>>> branch 'main' of https://github.com/niccolodidoni/TelcoService_SC42
