CREATE DATABASE  IF NOT EXISTS `telcoservice_db`;
USE `telcoservice_db`;

DROP TABLE IF EXISTS `service`;

CREATE TABLE `service` (
  `ID` int AUTO_INCREMENT PRIMARY KEY ,
  `TYPE` enum('FIXED_PHONE', 'MOBILE_PHONE', 'FIXED_INTERNET', 'MOBILE_INTERNET'),
  `EXPIRATION_DATE` date DEFAULT NULL  -- NULL = it never expires
);